"""Static catalog data for DFIR Iris MCP helper tools.

The data is kept in a dedicated module so it can be loaded by tools and
optionally reused elsewhere without pulling network data from DFIR Iris.
"""

from __future__ import annotations

# Validation hints mapped by IOC type id
IOC_VALIDATIONS: dict[str, dict[str, str]] = {
    "authentihash": {"validation_regex": r"[a-f0-9]{64}", "validation_expectation": "64 hexadecimal characters"},
    "filename|authentihash": {"validation_regex": r".+\|[a-f0-9]{64}", "validation_expectation": "filename|64 hexadecimal characters"},
    "filename|imphash": {"validation_regex": r".+\|[a-f0-9]{32}", "validation_expectation": "filename|32 hexadecimal characters"},
    "filename|md5": {"validation_regex": r".+\|[a-f0-9]{32}", "validation_expectation": "filename|32 hexadecimal characters"},
    "filename|pehash": {"validation_regex": r".+\|[a-f0-9]{40}", "validation_expectation": "filename|40 hexadecimal characters"},
    "filename|sha1": {"validation_regex": r".+\|[a-f0-9]{40}", "validation_expectation": "filename|40 hexadecimal characters"},
    "filename|sha224": {"validation_regex": r".+\|[a-f0-9]{56}", "validation_expectation": "filename|56 hexadecimal characters"},
    "filename|sha256": {"validation_regex": r".+\|[a-f0-9]{64}", "validation_expectation": "filename|64 hexadecimal characters"},
    "filename|sha3-224": {"validation_regex": r".+\|[a-f0-9]{56}", "validation_expectation": "filename|56 hexadecimal characters"},
    "filename|sha3-256": {"validation_regex": r".+\|[a-f0-9]{64}", "validation_expectation": "filename|64 hexadecimal characters"},
    "filename|sha3-384": {"validation_regex": r".+\|[a-f0-9]{96}", "validation_expectation": "filename|96 hexadecimal characters"},
    "filename|sha3-512": {"validation_regex": r".+\|[a-f0-9]{128}", "validation_expectation": "filename|128 hexadecimal characters"},
    "filename|sha384": {"validation_regex": r".+\|[a-f0-9]{96}", "validation_expectation": "filename|96 hexadecimal characters"},
    "filename|sha512": {"validation_regex": r".+\|[a-f0-9]{128}", "validation_expectation": "filename|128 hexadecimal characters"},
    "filename|sha512/224": {"validation_regex": r".+\|[a-f0-9]{56}", "validation_expectation": "filename|56 hexadecimal characters"},
    "filename|sha512/256": {"validation_regex": r".+\|[a-f0-9]{64}", "validation_expectation": "filename|64 hexadecimal characters"},
    "filename|tlsh": {"validation_regex": r".+\|t?[a-f0-9]{35,}", "validation_expectation": "filename|at least 35 hexadecimal characters; optional 't' prefix"},
    "git-commit-id": {"validation_regex": r"[a-f0-9]{40}", "validation_expectation": "40 hexadecimal characters"},
    "hassh-md5": {"validation_regex": r"[a-f0-9]{32}", "validation_expectation": "32 hexadecimal characters"},
    "hasshserver-md5": {"validation_regex": r"[a-f0-9]{32}", "validation_expectation": "32 hexadecimal characters"},
    "imphash": {"validation_regex": r"[a-f0-9]{32}", "validation_expectation": "32 hexadecimal characters"},
    "ja3-fingerprint-md5": {"validation_regex": r"[a-f0-9]{32}", "validation_expectation": "32 hexadecimal characters"},
    "jarm-fingerprint": {"validation_regex": r"[a-f0-9]{62}", "validation_expectation": "62 hexadecimal characters"},
    "md5": {"validation_regex": r"[a-f0-9]{32}", "validation_expectation": "32 hexadecimal characters"},
    "mutex": {"validation_expectation": "Use format \\BaseNamedObjects<Mutex>"},
    "named pipe": {"validation_expectation": "Use format .\\pipe<PipeName>"},
    "pehash": {"validation_regex": r"[a-f0-9]{40}", "validation_expectation": "40 hexadecimal characters"},
    "sha1": {"validation_regex": r"[a-f0-9]{40}", "validation_expectation": "40 hexadecimal characters"},
    "sha224": {"validation_regex": r"[a-f0-9]{56}", "validation_expectation": "56 hexadecimal characters"},
    "sha256": {"validation_regex": r"[a-f0-9]{64}", "validation_expectation": "64 hexadecimal characters"},
    "sha3-224": {"validation_regex": r"[a-f0-9]{56}", "validation_expectation": "56 hexadecimal characters"},
    "sha3-256": {"validation_regex": r"[a-f0-9]{64}", "validation_expectation": "64 hexadecimal characters"},
    "sha3-384": {"validation_regex": r"[a-f0-9]{96}", "validation_expectation": "96 hexadecimal characters"},
    "sha3-512": {"validation_regex": r"[a-f0-9]{128}", "validation_expectation": "128 hexadecimal characters"},
    "sha384": {"validation_regex": r"[a-f0-9]{96}", "validation_expectation": "96 hexadecimal characters"},
    "sha512": {"validation_regex": r"[a-f0-9]{128}", "validation_expectation": "128 hexadecimal characters"},
    "sha512/224": {"validation_regex": r"[a-f0-9]{56}", "validation_expectation": "56 hexadecimal characters"},
    "sha512/256": {"validation_regex": r"[a-f0-9]{64}", "validation_expectation": "64 hexadecimal characters"},
    "telfhash": {"validation_regex": r"[a-f0-9]{70}", "validation_expectation": "70 hexadecimal characters"},
    "tlsh": {"validation_regex": r"t?[a-f0-9]{35,}", "validation_expectation": "At least 35 hexadecimal characters; optional 't' prefix"},
    "x509-fingerprint-md5": {"validation_regex": r"[a-f0-9]{32}", "validation_expectation": "32 hexadecimal characters"},
    "x509-fingerprint-sha1": {"validation_regex": r"[a-f0-9]{40}", "validation_expectation": "40 hexadecimal characters"},
    "x509-fingerprint-sha256": {"validation_regex": r"[a-f0-9]{64}", "validation_expectation": "64 hexadecimal characters"},
}

IOC_TYPES_BASE: list[dict[str, str]] = [
    {"type": "AS", "description": "Autonomous system"},
    {"type": "aba-rtn", "description": "ABA routing transit number"},
    {"type": "account", "description": "Account of any type"},
    {"type": "anonymised", "description": "Anonymised value described with the anonymisation object via a relationship"},
    {"type": "attachment", "description": "Attachment with external information"},
    {"type": "authentihash", "description": "Authenticode executable signature hash"},
    {"type": "boolean", "description": "Boolean value to be used in objects"},
    {"type": "btc", "description": "Bitcoin address"},
    {"type": "campaign-id", "description": "Associated campaign ID"},
    {"type": "campaign-name", "description": "Associated campaign name"},
    {"type": "cdhash", "description": "Apple Code Directory Hash identifying a code-signed Mach-O executable"},
    {"type": "chrome-extension-id", "description": "Chrome extension id"},
    {"type": "community-id", "description": "Community ID flow hash to map multiple traffic monitors into a common flow id"},
    {"type": "cookie", "description": "HTTP cookie often stored on the user web client (session or authentication)"},
    {"type": "dash", "description": "Dash address"},
    {"type": "datetime", "description": "Datetime in ISO 8601 format"},
    {"type": "dkim", "description": "DKIM public key"},
    {"type": "dkim-signature", "description": "DKIM signature"},
    {"type": "dns-soa-email", "description": "SOA record contact email for a DNS zone"},
    {"type": "domain", "description": "Domain name"},
    {"type": "domain|ip", "description": "Domain name and its resolved IP address separated by |"},
    {"type": "email", "description": "Email address"},
    {"type": "email-attachment", "description": "File name of the email attachment"},
    {"type": "email-body", "description": "Email body"},
    {"type": "email-dst", "description": "Recipient email address"},
    {"type": "email-dst-display-name", "description": "Recipient display name"},
    {"type": "email-header", "description": "Email header"},
    {"type": "email-message-id", "description": "Email message ID"},
    {"type": "email-mime-boundary", "description": "Email MIME boundary separating parts"},
    {"type": "email-reply-to", "description": "Email reply-to header"},
    {"type": "email-src", "description": "Sender email address"},
    {"type": "email-src-display-name", "description": "Sender display name"},
    {"type": "email-subject", "description": "Email subject"},
    {"type": "email-thread-index", "description": "Email thread index header"},
    {"type": "email-x-mailer", "description": "Email X-Mailer header"},
    {"type": "favicon-mmh3", "description": "Murmur3 hash of a favicon (as used in Shodan)"},
    {"type": "filename", "description": "Filename"},
    {"type": "filename-pattern", "description": "Pattern in the name of a file"},
    {"type": "filename|authentihash", "description": "Filename and authentihash separated by |"},
    {"type": "filename|impfuzzy", "description": "Filename and import fuzzy hash separated by |"},
    {"type": "filename|imphash", "description": "Filename and imphash separated by |"},
    {"type": "filename|md5", "description": "Filename and MD5 hash separated by |"},
    {"type": "filename|pehash", "description": "Filename and PEhash separated by |"},
    {"type": "filename|sha1", "description": "Filename and SHA1 hash separated by |"},
    {"type": "filename|sha224", "description": "Filename and SHA-224 hash separated by |"},
    {"type": "filename|sha256", "description": "Filename and SHA256 hash separated by |"},
    {"type": "filename|sha3-224", "description": "Filename and SHA3-224 hash separated by |"},
    {"type": "filename|sha3-256", "description": "Filename and SHA3-256 hash separated by |"},
    {"type": "filename|sha3-384", "description": "Filename and SHA3-384 hash separated by |"},
    {"type": "filename|sha3-512", "description": "Filename and SHA3-512 hash separated by |"},
    {"type": "filename|sha384", "description": "Filename and SHA-384 hash separated by |"},
    {"type": "filename|sha512", "description": "Filename and SHA-512 hash separated by |"},
    {"type": "filename|sha512/224", "description": "Filename and SHA-512/224 hash separated by |"},
    {"type": "filename|sha512/256", "description": "Filename and SHA-512/256 hash separated by |"},
    {"type": "filename|ssdeep", "description": "Filename and ssdeep checksum separated by |"},
    {"type": "filename|tlsh", "description": "Filename and TLSH separated by |"},
    {"type": "filename|vhash", "description": "Filename and VirusTotal vhash separated by |"},
    {"type": "first-name", "description": "First name of a natural person"},
    {"type": "float", "description": "Floating point value"},
    {"type": "full-name", "description": "Full name of a natural person"},
    {"type": "gene", "description": "GENE - Go Evtx signature engine"},
    {"type": "git-commit-id", "description": "Git commit ID"},
    {"type": "github-organisation", "description": "GitHub organisation"},
    {"type": "github-repository", "description": "GitHub repository"},
    {"type": "github-username", "description": "GitHub user name"},
    {"type": "hassh-md5", "description": "HASSH client fingerprint MD5"},
    {"type": "hasshserver-md5", "description": "HASSH server fingerprint MD5"},
    {"type": "hex", "description": "Hexadecimal value"},
    {"type": "hostname", "description": "Full host/DNS name"},
    {"type": "hostname|port", "description": "Hostname and port number separated by |"},
    {"type": "http-method", "description": "HTTP method used by the malware (POST, GET, etc.)"},
    {"type": "iban", "description": "International Bank Account Number"},
    {"type": "identity-card-number", "description": "Identity card number"},
    {"type": "impfuzzy", "description": "Import fuzzy hash"},
    {"type": "imphash", "description": "Import hash (imphash)"},
    {"type": "ip-any", "description": "Source or destination IP address"},
    {"type": "ip-dst", "description": "Destination IP address"},
    {"type": "ip-dst|port", "description": "Destination IP and port separated by |"},
    {"type": "ip-src", "description": "Source IP address"},
    {"type": "ip-src|port", "description": "Source IP and port separated by |"},
    {"type": "ja3-fingerprint-md5", "description": "JA3 TLS client fingerprint (MD5)"},
    {"type": "jabber-id", "description": "Jabber ID"},
    {"type": "jarm-fingerprint", "description": "JARM TLS server fingerprint"},
    {"type": "kusto-query", "description": "Azure Kusto query"},
    {"type": "link", "description": "Link to external information"},
    {"type": "mac-address", "description": "MAC address"},
    {"type": "mac-eui-64", "description": "MAC EUI-64 address"},
    {"type": "malware-sample", "description": "Attachment containing encrypted malware sample"},
    {"type": "malware-type", "description": "Malware type"},
    {"type": "md5", "description": "MD5 checksum"},
    {"type": "middle-name", "description": "Middle name of a natural person"},
    {"type": "mime-type", "description": "MIME/media content type"},
    {"type": "mobile-application-id", "description": "Mobile application identifier"},
    {"type": "mutex", "description": "Mutex"},
    {"type": "named pipe", "description": "Named pipe"},
    {"type": "other", "description": "Other attribute"},
    {"type": "file-path", "description": "File path"},
    {"type": "pattern-in-file", "description": "Pattern in file that identifies the malware"},
    {"type": "pattern-in-memory", "description": "Pattern in memory dump that identifies the malware"},
    {"type": "pattern-in-traffic", "description": "Pattern in network traffic that identifies the malware"},
    {"type": "pdb", "description": "Microsoft Program Database (PDB) path"},
    {"type": "pehash", "description": "PEhash calculated from a PE executable"},
    {"type": "pgp-private-key", "description": "PGP private key"},
    {"type": "pgp-public-key", "description": "PGP public key"},
    {"type": "phone-number", "description": "Telephone number"},
    {"type": "port", "description": "Port number"},
    {"type": "process-state", "description": "State of a process"},
    {"type": "prtn", "description": "Premium-rate telephone number"},
    {"type": "regkey", "description": "Registry key or value"},
    {"type": "regkey|value", "description": "Registry value and data separated by |"},
    {"type": "sha1", "description": "SHA1 checksum"},
    {"type": "sha224", "description": "SHA-224 checksum"},
    {"type": "sha256", "description": "SHA-256 checksum"},
    {"type": "sha3-224", "description": "SHA3-224 checksum"},
    {"type": "sha3-256", "description": "SHA3-256 checksum"},
    {"type": "sha3-384", "description": "SHA3-384 checksum"},
    {"type": "sha3-512", "description": "SHA3-512 checksum"},
    {"type": "sha384", "description": "SHA-384 checksum"},
    {"type": "sha512", "description": "SHA-512 checksum"},
    {"type": "sha512/224", "description": "SHA-512/224 checksum"},
    {"type": "sha512/256", "description": "SHA-512/256 checksum"},
    {"type": "sigma", "description": "Sigma rule"},
    {"type": "size-in-bytes", "description": "Size expressed in bytes"},
    {"type": "snort", "description": "Snort IDS rule"},
    {"type": "ssdeep", "description": "ssdeep checksum"},
    {"type": "ssh-fingerprint", "description": "SSH key fingerprint"},
    {"type": "stix2-pattern", "description": "STIX 2 pattern"},
    {"type": "target-email", "description": "Attack target email(s)"},
    {"type": "target-external", "description": "External target organisations affected"},
    {"type": "target-location", "description": "Attack target physical location(s)"},
    {"type": "target-machine", "description": "Attack target machine name(s)"},
    {"type": "target-org", "description": "Attack target department or organisation(s)"},
    {"type": "target-user", "description": "Attack target username(s)"},
    {"type": "telfhash", "description": "telfhash symbol hash for ELF files"},
    {"type": "text", "description": "Name, ID or reference"},
    {"type": "threat-actor", "description": "Threat actor identifier"},
    {"type": "tlsh", "description": "TLSH (Trend Micro Locality Sensitive Hash)"},
    {"type": "travel-details", "description": "Travel details"},
    {"type": "twitter-id", "description": "Twitter ID"},
    {"type": "uri", "description": "Uniform Resource Identifier"},
    {"type": "url", "description": "URL"},
    {"type": "user-agent", "description": "HTTP user agent"},
    {"type": "vhash", "description": "VirusTotal vhash checksum"},
    {"type": "vulnerability", "description": "Vulnerability reference"},
    {"type": "weakness", "description": "Weakness reference"},
    {"type": "whois-creation-date", "description": "Domain creation date from WHOIS"},
    {"type": "whois-registrant-email", "description": "WHOIS registrant email"},
    {"type": "whois-registrant-name", "description": "WHOIS registrant name"},
    {"type": "whois-registrant-org", "description": "WHOIS registrant organisation"},
    {"type": "whois-registrant-phone", "description": "WHOIS registrant phone number"},
    {"type": "whois-registrar", "description": "Domain registrar from WHOIS"},
    {"type": "windows-scheduled-task", "description": "Windows scheduled task"},
    {"type": "windows-service-displayname", "description": "Windows service display name"},
    {"type": "windows-service-name", "description": "Windows service name"},
    {"type": "x509-fingerprint-md5", "description": "X.509 certificate fingerprint (MD5)"},
    {"type": "x509-fingerprint-sha1", "description": "X.509 certificate fingerprint (SHA-1)"},
    {"type": "x509-fingerprint-sha256", "description": "X.509 certificate fingerprint (SHA-256)"},
    {"type": "xmr", "description": "Monero address"},
    {"type": "yara", "description": "YARA signature"},
    {"type": "zeek", "description": "Zeek NIDS rule"},
]


def _build_ioc_types() -> list[dict[str, str]]:
    merged: list[dict[str, str]] = []
    for item in IOC_TYPES_BASE:
        enriched = dict(item)
        if item["type"] in IOC_VALIDATIONS:
            enriched.update(IOC_VALIDATIONS[item["type"]])
        merged.append(enriched)
    return merged


IOC_TYPES: list[dict[str, str]] = _build_ioc_types()

ASSET_TYPES: list[dict[str, str]] = [
    {
        "asset_name": "Account",
        "asset_description": "Generic Account",
        "asset_icon_not_compromised": "user.png",
        "asset_icon_compromised": "ioc_user.png",
    },
    {
        "asset_name": "Firewall",
        "asset_description": "Firewall",
        "asset_icon_not_compromised": "firewall.png",
        "asset_icon_compromised": "ioc_firewall.png",
    },
    {
        "asset_name": "Linux - Server",
        "asset_description": "Linux server",
        "asset_icon_not_compromised": "server.png",
        "asset_icon_compromised": "ioc_server.png",
    },
    {
        "asset_name": "Linux - Computer",
        "asset_description": "Linux computer",
        "asset_icon_not_compromised": "desktop.png",
        "asset_icon_compromised": "ioc_desktop.png",
    },
    {
        "asset_name": "Linux Account",
        "asset_description": "Linux Account",
        "asset_icon_not_compromised": "user.png",
        "asset_icon_compromised": "ioc_user.png",
    },
    {
        "asset_name": "Mac - Computer",
        "asset_description": "Mac computer",
        "asset_icon_not_compromised": "desktop.png",
        "asset_icon_compromised": "ioc_desktop.png",
    },
    {
        "asset_name": "Phone - Android",
        "asset_description": "Android phone",
        "asset_icon_not_compromised": "phone.png",
        "asset_icon_compromised": "ioc_phone.png",
    },
    {
        "asset_name": "Phone - IOS",
        "asset_description": "Apple phone",
        "asset_icon_not_compromised": "phone.png",
        "asset_icon_compromised": "ioc_phone.png",
    },
    {
        "asset_name": "Windows - Computer",
        "asset_description": "Standard Windows computer",
        "asset_icon_not_compromised": "windows_desktop.png",
        "asset_icon_compromised": "ioc_windows_desktop.png",
    },
    {
        "asset_name": "Windows - Server",
        "asset_description": "Standard Windows server",
        "asset_icon_not_compromised": "windows_server.png",
        "asset_icon_compromised": "ioc_windows_server.png",
    },
    {
        "asset_name": "Windows - DC",
        "asset_description": "Domain Controller",
        "asset_icon_not_compromised": "windows_server.png",
        "asset_icon_compromised": "ioc_windows_server.png",
    },
    {
        "asset_name": "Router",
        "asset_description": "Router",
        "asset_icon_not_compromised": "router.png",
        "asset_icon_compromised": "ioc_router.png",
    },
    {
        "asset_name": "Switch",
        "asset_description": "Switch",
        "asset_icon_not_compromised": "switch.png",
        "asset_icon_compromised": "ioc_switch.png",
    },
    {
        "asset_name": "VPN",
        "asset_description": "VPN",
        "asset_icon_not_compromised": "vpn.png",
        "asset_icon_compromised": "ioc_vpn.png",
    },
    {
        "asset_name": "WAF",
        "asset_description": "Web application firewall",
        "asset_icon_not_compromised": "firewall.png",
        "asset_icon_compromised": "ioc_firewall.png",
    },
    {
        "asset_name": "Windows Account - Local",
        "asset_description": "Windows Account - Local",
        "asset_icon_not_compromised": "user.png",
        "asset_icon_compromised": "ioc_user.png",
    },
    {
        "asset_name": "Windows Account - Local - Admin",
        "asset_description": "Windows Account - Local - Admin",
        "asset_icon_not_compromised": "user.png",
        "asset_icon_compromised": "ioc_user.png",
    },
    {
        "asset_name": "Windows Account - AD",
        "asset_description": "Windows Account - AD",
        "asset_icon_not_compromised": "user.png",
        "asset_icon_compromised": "ioc_user.png",
    },
    {
        "asset_name": "Windows Account - AD - Admin",
        "asset_description": "Windows Account - AD - Admin",
        "asset_icon_not_compromised": "user.png",
        "asset_icon_compromised": "ioc_user.png",
    },
    {
        "asset_name": "Windows Account - AD - krbtgt",
        "asset_description": "Windows Account - AD - krbtgt",
        "asset_icon_not_compromised": "user.png",
        "asset_icon_compromised": "ioc_user.png",
    },
    {
        "asset_name": "Windows Account - AD - Service",
        "asset_description": "Windows Account - AD - Service",
        "asset_icon_not_compromised": "user.png",
        "asset_icon_compromised": "ioc_user.png",
    },
]

ANALYSIS_STATUSES: list[dict[str, str]] = [
    {"name": "Unspecified", "description": "Analysis status not set"},
    {"name": "To be done", "description": "Pending analysis"},
    {"name": "Started", "description": "Analysis started"},
    {"name": "Pending", "description": "Blocked or waiting"},
    {"name": "Canceled", "description": "Analysis canceled"},
    {"name": "Done", "description": "Analysis completed"},
]

ALERT_RESOLUTION_STATUSES: list[dict[str, str]] = [
    {"name": "False Positive", "description": "The alert was a false positive"},
    {"name": "True Positive With Impact", "description": "True positive with impact"},
    {"name": "True Positive Without Impact", "description": "True positive without impact"},
    {"name": "Not Applicable", "description": "The alert is not applicable"},
    {"name": "Unknown", "description": "Unknown resolution status"},
    {"name": "Legitimate", "description": "The alert is acceptable and expected"},
]

TASK_STATUSES: list[dict[str, str]] = [
    {"name": "To do", "description": "", "bscolor": "danger"},
    {"name": "In progress", "description": "", "bscolor": "warning"},
    {"name": "On hold", "description": "", "bscolor": "muted"},
    {"name": "Done", "description": "", "bscolor": "success"},
    {"name": "Canceled", "description": "", "bscolor": "muted"},
]

SEVERITIES: list[dict[str, str]] = [
    {"name": "Unspecified", "description": "Unspecified"},
    {"name": "Informational", "description": "Informational"},
    {"name": "Low", "description": "Low"},
    {"name": "Medium", "description": "Medium"},
    {"name": "High", "description": "High"},
    {"name": "Critical", "description": "Critical"},
]

ALERT_STATUSES: list[dict[str, str]] = [
    {"name": "Unspecified", "description": "Unspecified"},
    {"name": "New", "description": "Alert is new and unassigned"},
    {"name": "Assigned", "description": "Alert is assigned and pending investigation"},
    {"name": "In progress", "description": "Alert is being investigated"},
    {"name": "Pending", "description": "Alert is in a pending state"},
    {"name": "Closed", "description": "Alert closed, no action taken"},
    {"name": "Merged", "description": "Alert merged into an existing case"},
    {"name": "Escalated", "description": "Alert converted to a new case"},
]

OS_TYPES: list[dict[str, str]] = [
    {"name": "Windows"},
    {"name": "Linux"},
    {"name": "AIX"},
    {"name": "MacOS"},
    {"name": "Apple iOS"},
    {"name": "Cisco iOS"},
    {"name": "Android"},
]

TLP_LEVELS: list[dict[str, str]] = [
    {"name": "red", "bscolor": "danger"},
    {"name": "amber", "bscolor": "warning"},
    {"name": "green", "bscolor": "success"},
    {"name": "clear", "bscolor": "black"},
    {"name": "amber+strict", "bscolor": "warning"},
]

EVIDENCE_TYPES: list[dict[str, str]] = [
    {"name": "Unspecified", "description": "Unspecified"},
    {"name": "HDD image - Generic", "description": "Generic copy of a hard drive"},
    {"name": "HDD image - DD - Other", "description": "DD copy of a hard drive"},
    {"name": "HDD image - DD - Windows", "description": "DD copy of a Windows hard drive"},
    {"name": "HDD image - DD - Unix", "description": "DD copy of a Unix hard drive"},
    {"name": "HDD image - DD - MacOS", "description": "DD copy of a MacOS hard drive"},
    {"name": "HDD image - E01 - Other", "description": "E01 acquisition of a hard drive"},
    {"name": "HDD image - E01 - Windows", "description": "E01 acquisition of a Windows hard drive"},
    {"name": "HDD image - E01 - Unix", "description": "E01 acquisition of a Unix hard drive"},
    {"name": "HDD image - E01 - MacOS", "description": "E01 acquisition of a MacOS hard drive"},
    {"name": "HDD image - AFF4 - Other", "description": "AFF4 acquisition of a hard drive"},
    {"name": "HDD image - AFF4 - Windows", "description": "AFF4 acquisition of a Windows hard drive"},
    {"name": "HDD image - AFF4 - Unix", "description": "AFF4 acquisition of a Unix hard drive"},
    {"name": "HDD image - AFF4 - MacOS", "description": "AFF4 acquisition of a MacOS hard drive"},
    {"name": "SSD image - Generic", "description": "Generic copy of a solid state drive"},
    {"name": "SSD image - DD - Other", "description": "DD copy of a solid state drive"},
    {"name": "SSD image - DD - Windows", "description": "DD copy of a Windows solid state drive"},
    {"name": "SSD image - DD - Unix", "description": "DD copy of a Unix solid state drive"},
    {"name": "SSD image - DD - MacOS", "description": "DD copy of a MacOS solid state drive"},
    {"name": "SSD image - E01 - Other", "description": "E01 copy of a solid state drive"},
    {"name": "SSD image - E01 - Windows", "description": "E01 copy of a Windows solid state drive"},
    {"name": "SSD image - E01 - Unix", "description": "E01 copy of a Unix solid state drive"},
    {"name": "SSD image - E01 - MacOS", "description": "E01 copy of a MacOS solid state drive"},
    {"name": "SSD image - AFF4 - Other", "description": "AFF4 copy of a solid state drive"},
    {"name": "SSD image - AFF4 - Windows", "description": "AFF4 copy of a Windows solid state drive"},
    {"name": "SSD image - AFF4 - Unix", "description": "AFF4 copy of a Unix solid state drive"},
    {"name": "SSD image - AFF4 - MacOS", "description": "AFF4 copy of a MacOS solid state drive"},
    {"name": "VM image - Generic", "description": "Generic VM image"},
    {"name": "VM image - Linux Server", "description": "Copy of a Linux Server VM"},
    {"name": "VM image - Windows Server", "description": "Copy of a Windows Server VM"},
    {"name": "Phone Image - Android", "description": "Copy of an Android phone"},
    {"name": "Phone Image - iPhone", "description": "Copy of an iPhone"},
    {"name": "Phone backup - Android (adb)", "description": "adb backup of an Android"},
    {"name": "Phone backup - iPhone (iTunes)", "description": "iTunes backup of an iPhone"},
    {"name": "Tablet Image - Android", "description": "Copy of an Android tablet"},
    {"name": "Tablet Image - iPad", "description": "Copy of an iPad tablet"},
    {"name": "Tablet backup - Android (adb)", "description": "adb backup of an Android tablet"},
    {"name": "Tablet backup - iPad (iTunes)", "description": "iTunes backup of an iPad"},
    {"name": "Collection - Velociraptor", "description": "Velociraptor collection"},
    {"name": "Collection - ORC", "description": "ORC collection"},
    {"name": "Collection - KAPE", "description": "KAPE collection"},
    {"name": "Memory acquisition - Physical RAM", "description": "Physical RAM acquisition"},
    {"name": "Memory acquisition - VMEM", "description": "vmem file"},
    {"name": "Logs - Linux", "description": "Standard Linux logs"},
    {"name": "Logs - Windows EVTX", "description": "Standard Windows EVTX logs"},
    {"name": "Logs - Windows EVT", "description": "Standard Windows EVT logs"},
    {"name": "Logs - MacOS", "description": "Standard MacOS logs"},
    {"name": "Logs - Generic", "description": "Generic logs"},
    {"name": "Logs - Firewall", "description": "Firewall logs"},
    {"name": "Logs - Proxy", "description": "Proxy logs"},
    {"name": "Logs - DNS", "description": "DNS logs"},
    {"name": "Logs - Email", "description": "Email logs"},
    {"name": "Executable - Windows (PE)", "description": "Generic Windows executable"},
    {"name": "Executable - Linux (ELF)", "description": "Generic Linux executable"},
    {"name": "Executable - MacOS (Mach-O)", "description": "Generic MacOS executable"},
    {"name": "Executable - Generic", "description": "Generic executable"},
    {"name": "Script - Generic", "description": "Generic script"},
    {"name": "Generic - Data blob", "description": "Generic blob of data"},
]

EVENT_CATEGORIES: list[dict[str, str]] = [
    {"name": "Unspecified", "description": "Unspecified"},
    {"name": "Legitimate", "description": "Legitimate"},
    {"name": "Remediation", "description": "Remediation"},
    {"name": "Initial Access", "description": "Initial Access"},
    {"name": "Execution", "description": "Execution"},
    {"name": "Persistence", "description": "Persistence"},
    {"name": "Privilege Escalation", "description": "Privilege Escalation"},
    {"name": "Defense Evasion", "description": "Defense Evasion"},
    {"name": "Credential Access", "description": "Credential Access"},
    {"name": "Discovery", "description": "Discovery"},
    {"name": "Lateral Movement", "description": "Lateral Movement"},
    {"name": "Collection", "description": "Collection"},
    {"name": "Command and Control", "description": "Command and Control"},
    {"name": "Exfiltration", "description": "Exfiltration"},
    {"name": "Impact", "description": "Impact"},
]

CATALOG: dict[str, list[dict[str, str]]] = {
    "iocs": IOC_TYPES,
    "assets": ASSET_TYPES,
    "analysis_statuses": ANALYSIS_STATUSES,
    "alert_resolution_statuses": ALERT_RESOLUTION_STATUSES,
    "task_statuses": TASK_STATUSES,
    "severities": SEVERITIES,
    "alert_statuses": ALERT_STATUSES,
    "evidence_types": EVIDENCE_TYPES,
    "event_categories": EVENT_CATEGORIES,
    "os_types": OS_TYPES,
    "tlp_levels": TLP_LEVELS,
}

__all__ = [
    "ALERT_RESOLUTION_STATUSES",
    "ALERT_STATUSES",
    "ANALYSIS_STATUSES",
    "ASSET_TYPES",
    "CATALOG",
    "EVENT_CATEGORIES",
    "EVIDENCE_TYPES",
    "IOC_TYPES",
    "OS_TYPES",
    "SEVERITIES",
    "TASK_STATUSES",
    "TLP_LEVELS",
]
